type BadgeHolder @entity {
  id: ID!
  holdings: JSON!
  badgesHeld: [BadgeAmount!]! @derivedFrom(field: "holder")
  totalAmount: BigInt!
  beranames: [Beraname!]! @derivedFrom(field: "owner")
}

type BadgeAmount @entity {
  id: ID!
  badgeId: String!
  amount: BigInt!
  holder: BadgeHolder!
}

type QueueBoost @entity {
  id: ID!
  user: String!
  validator: String!
  amount: BigInt!
  timestamp: BigInt!
}

type ActivateBoost @entity {
  id: ID!
  user: String!
  validator: String!
  amount: BigInt!
  timestamp: BigInt!
}

type CancelBoost @entity {
  id: ID!
  user: String!
  validator: String!
  amount: BigInt!
  timestamp: BigInt!
}

type DropBoost @entity {
  id: ID!
  user: String!
  validator: String!
  amount: BigInt!
  timestamp: BigInt!
}

type Beraname @entity {
  id: ID!
  name: String!
  owner: BadgeHolder!
  whois: String!
  expiry: BigInt!
  metadataURI: String!
}

type Distribution @entity {
  id: ID!
  valCoinbase: String!
  blockNumber: BigInt!
  receiver: String!
  amount: BigInt!
  timestamp: BigInt!
  rewards: [DistributionReward!]! @derivedFrom(field: "distribution")
}

type DistributionReward @entity {
  id: ID!
  distribution: Distribution!
  token: String!
  amount: BigInt!
}
