type BadgeHolder @entity {
  id: ID!
  holdings: JSON!
  badgesHeld: [BadgeAmount!]! @derivedFrom(field: "holder")
  totalAmount: BigInt!
  beranames: [Beraname!]! @derivedFrom(field: "owner")
}

type BadgeAmount @entity {
  id: ID!
  badgeId: String!
  amount: BigInt!
  holder: BadgeHolder!
}

type QueueBoost @entity {
  id: ID!
  user: String!
  validator: String!
  amount: BigInt!
  timestamp: BigInt!
}

type ActivateBoost @entity {
  id: ID!
  user: String!
  validator: String!
  amount: BigInt!
  timestamp: BigInt!
}

type Beraname @entity {
  id: ID!
  name: String!
  owner: BadgeHolder!
  whois: String!
  expiry: BigInt!
  metadataURI: String!
}
